<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DesignmovesApplication\Module'                                            => __DIR__ . '/Module.php',
  'DesignmovesApplication\Controller\IndexController'                        => __DIR__ . '/src/DesignmovesApplication/Controller/IndexController.php',
  'DesignmovesApplication\Exception\ExceptionInterface'                      => __DIR__ . '/src/DesignmovesApplication/Exception/ExceptionInterface.php',
  'DesignmovesApplication\Factory\Listener\ExceptionTemplateListenerFactory' => __DIR__ . '/src/DesignmovesApplication/Factory/Listener/ExceptionTemplateListenerFactory.php',
  'DesignmovesApplication\Factory\Options\ModuleOptionsFactory'              => __DIR__ . '/src/DesignmovesApplication/Factory/Options/ModuleOptionsFactory.php',
  'DesignmovesApplication\Listener\Exception\ExceptionInterface'             => __DIR__ . '/src/DesignmovesApplication/Listener/Exception/ExceptionInterface.php',
  'DesignmovesApplication\Listener\Exception\LogicException'                 => __DIR__ . '/src/DesignmovesApplication/Listener/Exception/LogicException.php',
  'DesignmovesApplication\Listener\ExceptionTemplateListener'                => __DIR__ . '/src/DesignmovesApplication/Listener/ExceptionTemplateListener.php',
  'DesignmovesApplication\Options\ModuleOptions'                             => __DIR__ . '/src/DesignmovesApplication/Options/ModuleOptions.php',
  'DesignmovesApplicationTest\Bootstrap'                                     => __DIR__ . '/test/Bootstrap.php',
  'DesignmovesApplicationTest\Controller\IndexControllerTest'                => __DIR__ . '/test/DesignmovesApplicationTest/Controller/IndexControllerTest.php',
  'DesignmovesApplicationTest\Factory\Listener\PageListenerFactoryTest'      => __DIR__ . '/test/DesignmovesApplicationTest/Factory/Listener/ExceptionTemplateListenerFactoryTest.php',
  'DesignmovesApplicationTest\Factory\Options\ModuleOptionsFactoryTest'      => __DIR__ . '/test/DesignmovesApplicationTest/Factory/Options/ModuleOptionsFactoryTest.php',
  'DesignmovesApplicationTest\Listener\Exception\LogicExceptionTest'         => __DIR__ . '/test/DesignmovesApplicationTest/Listener/Exception/LogicExceptionTest.php',
  'DesignmovesApplicationTest\Listener\ExceptionTemplateListenerTest'        => __DIR__ . '/test/DesignmovesApplicationTest/Listener/ExceptionTemplateListenerTest.php',
  'DesignmovesApplicationTest\Options\ModuleOptionsTest'                     => __DIR__ . '/test/DesignmovesApplicationTest/Options/ModuleOptionsTest.php',
);
