<?php $this->headTitle($this->content); ?>

<h1 class="center"><?php echo $this->escapeHtml($this->content); ?></h1>
<p class="center"><?php echo $this->escapeHtml($this->content); ?></p>
<p class="center">File: <code><?php
$offset = strrpos(__FILE__, 'module');
if (false === $offset) {
    $offset = strrpos(__FILE__, 'vendor');
}

$template = substr(__FILE__, $offset + 7);
echo $this->escapeHtml($template);
?></code></p>

<?php
$exceptionCode = 404;

throw new Exception(sprintf(
    'Exception thrown in "%s" with exception code "%s"',
    basename(__FILE__),
    $exceptionCode
), $exceptionCode);

