<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <?php echo $this->headMeta()->setCharset('UTF-8') . PHP_EOL; ?>
    <?php echo $this->headTitle() . PHP_EOL; ?>
    <style>
    <!--
    html {
        background: #CCC;
        display: table;
        font-size: 62.5%;
        height: 100%;
        margin: 0 auto;
    }
    body {
        display: table-cell;
        font: normal 2em/1.4 Georgia;
        padding: 1em;
        vertical-align: middle;
    }
    #wrapper {
        background: #333;
        border: 1px solid #EFEFEF;
        border-radius: .3em;
        box-shadow: 0px 0px 10px 2px #333;
        color: #EFEFEF;
        max-width: 950px;
        padding: 1em 2em;
        text-shadow: 1px 1px 1px #000;
    }
    h1 {
        margin: 0;
    }
    p {
        margin: 1em 0 0;
    }
    pre {
        overflow: hidden;
        text-align: left;
    }
    pre:hover {
        overflow: auto;
    }
    .center {
        text-align: center;
    }
    -->
    </style>
  </head>

  <body>
    <div id="wrapper">
      <?php echo $this->content; ?>
    </div>
  </body>
</html>
